services:
  app:
    build: .
    container_name: job-app
    volumes:
      - .:/home/environment
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ["bash"]  # デタッチ以外ではシェルを起動
    environment:
      RAILS_ENV: development
      # REDIS_URL: redis://redis:6379/1
  #   depends_on:
  #     - redis

  # redis:
  #   container_name: redis-master
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
