services:
  redis-shard1-master:
    image: redis:latest
    container_name: redis-shard1-master
    ports:
      - "6380:6379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.100

  redis-shard1-slave:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-shard1-slave
    depends_on:
      - redis-shard1-master
    environment:
      - REDIS_MASTER_HOST=172.23.0.100
      - REDIS_MASTER_PORT=6379
    networks:
      redis-network:
        ipv4_address: 172.23.0.101
    command: ["slave-entrypoint.sh"]

  redis-shard1-sentinel1:
    image: redis:latest
    container_name: redis-shard1-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard1-master
    ports:
      - "26380:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.110
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.100
      - REDIS_MASTER_PORT=6379

  redis-shard1-sentinel2:
    image: redis:latest
    container_name: redis-shard1-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard1-master
    ports:
      - "26381:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.111
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.100
      - REDIS_MASTER_PORT=6379

  redis-shard1-sentinel3:
    image: redis:latest
    container_name: redis-shard1-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard1-master
    ports:
      - "26382:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.112
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.100
      - REDIS_MASTER_PORT=6379

  redis-shard2-master:
    image: redis:latest
    container_name: redis-shard2-master
    ports:
      - "6381:6379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.200

  redis-shard2-slave:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-shard2-slave
    depends_on:
      - redis-shard2-master
    environment:
      - REDIS_MASTER_HOST=172.23.0.200
      - REDIS_MASTER_PORT=6379
    networks:
      redis-network:
        ipv4_address: 172.23.0.201
    command: ["slave-entrypoint.sh"]

  redis-shard2-sentinel1:
    image: redis:latest
    container_name: redis-shard2-sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard2-master
    ports:
      - "26390:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.210
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.200
      - REDIS_MASTER_PORT=6379

  redis-shard2-sentinel2:
    image: redis:latest
    container_name: redis-shard2-sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard2-master
    ports:
      - "26391:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.211
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.200
      - REDIS_MASTER_PORT=6379

  redis-shard2-sentinel3:
    image: redis:latest
    container_name: redis-shard2-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    restart: always
    depends_on:
      - redis-shard2-master
    ports:
      - "26392:26379"
    networks:
      redis-network:
        ipv4_address: 172.23.0.212
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    environment:
      - REDIS_MASTER_HOST=172.23.0.200
      - REDIS_MASTER_PORT=6379

  app:
    build:
      context: .
      dockerfile: Dockerfile.rails
    container_name: rails-app
    volumes:
      - ./rails_app:/app
    depends_on:
      - redis-shard1-master
      - redis-shard1-slave
      - redis-shard1-sentinel1
      - redis-shard1-sentinel2
      - redis-shard1-sentinel3
      - redis-shard2-master
      - redis-shard2-slave
      - redis-shard2-sentinel1
      - redis-shard2-sentinel2
      - redis-shard2-sentinel3
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      redis-network:
        ipv4_address: 172.23.0.104

networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
