services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-slave1:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-slave1
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    networks:
      - redis-network
    command: ["slave-entrypoint.sh"]
    
  redis-slave2:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis-slave2
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    networks:
      - redis-network
    command: ["slave-entrypoint.sh"]

  # redis-sentinel:
  #   image: redis:latest
  #   container_name: redis-sentinel
  #   command: redis-sentinel /usr/local/etc/redis/sentinel.conf
  #   depends_on:
  #     - redis-master
  #     - redis-slave1
  #     - redis-slave2
  #   ports:
  #     - "26379:26379"
  #   networks:
  #     - redis-network
  #   volumes:
  #     - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile.rails
    container_name: rails-app
    volumes:
      - ./rails_app:/app
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
      # - redis-sentinel
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - redis-network

networks:
  redis-network:
