FROM ruby:3.1

RUN apt-get update -qq && apt-get install -y \
  build-essential libpq-dev nodejs yarn

RUN gem install bundler && gem install rails -v 7.0.4.3

WORKDIR /app

EXPOSE 3000

CMD ["bash"]
