development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: your_app_development

# production:
  # adapter: redis
  # url: redis://localhost:6379/1  # 本番環境でもRedisを使用
  # channel_prefix: your_app_production
  # セキュリティやパフォーマンスを向上させるために追加設定も可能です
